apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8080
    targetPort: 8080
  - name: ui
    port: 4200
    targetPort: 4200
  selector:
    app: fortune
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: fortune
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fortune
        tier: frontend
    spec:
      containers:
      - name: fortune
        image: gokskrish/fortune
        ports:
        - containerPort: 8080
      - name: fortune-ui
        image: gokskrish/fortune-ui
        ports:
        - containerPort: 4200